- name: install and start apache
  hosts: us 
  remote_user: ec2-user 
  sudo: true
  vars:
     httpd_port: 80
  #sudo_user: root
  tasks:
    - name: yum apache 
      yum: name=httpd state=latest
    #  sudo: yes
    #- name: apache config
    #  template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    #  sudo: yes
    - name: ensure apache is running
      service: name=httpd state=running
    #  sudo: yes
    - name: insert iptables rule for httpd
      lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
                  line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
      notify: restart iptables

