---
# This playbook deploys the whole application stack in this site.  

#- name: apply common configuration to all nodes
#  hosts: webservers 
#  remote_user: ec2-user 
#  sudo: true
#  roles:
#    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ec2-user
  sudo: true
  roles:
    - web

